Parameters:
  # Existing Bucket name
  PipelineID:
    Description: Existing Bucket name
    Type: String
    Default: circlecibucket1455

Resources:
  CloudFrontOriginAccessIdentity:
    Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Origin Access Identity for Serverless Static Website

  WebpageCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub "${PipelineID}.s3-website-us-east-1.amazonaws.com"
            Id: webpage
            CustomOriginConfig:
              OriginProtocolPolicy: "http-only"
              HTTPPort: '80'
              HTTPSPort: '443'
        Enabled: True
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: False
          TargetOriginId: webpage
          ViewerProtocolPolicy: allow-all

Outputs:
  PipelineID:
    Value: !Sub ${PipelineID}
    Export:
      Name: PipelineID